### ISSUE TITLE
"TypeError: 'NoneType' object is not iterable" on updating/installing AUR packages via aurutils

### ISSUE THREAD

**Issue by NRGDEAD** [wesbarnett/snap-pac#58]
**Describe the bug**
snap-pac crashes about every other time on my desktop PC when updating/installing AUR packages via aurutils. It works just fine on my laptop, which runs *mostly* the same software. When I then re-run the commands, it works once. Only to crash again for the next time it's run. It seemingly works fine when updating/installing regular packages via pacman.
`python 3.12.4-1` is installed.

```
:: Running pre-transaction hooks...
(1/1) Performing snapper pre snapshots for the following configurations...
Traceback (most recent call last):
  File "/usr/share/libalpm/scripts/snap-pac", line 191, in <module>
    config_processor = ConfigProcessor(args.snap_pac_ini, args.type)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/libalpm/scripts/snap-pac", line 76, in __init__
    self.packages = [line.rstrip("\n") for line in sys.stdin]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
error: command failed to execute correctly
error: failed to commit transaction (failed to run transaction hooks)
Errors occurred, no packages were upgraded.
```
I would bet this is due to something wrong on my end, but I have no clue what the cause could be. So any tip for the right direction would be much appreciated. :-)

Cheers
NRG

**Comment by NRGDEAD** [comment]
Small correction: it also fails on my laptop. I just less often compiled AUR packages there.
